export interface GraphRelation {
  id: string;
  source: string;
  target: string;
  type: 'is-used-for' | 'is-compatible-with' | 'compares-to' | 'improves-on' | 'requires' | 'enhances';
  label: Record<string, string>;
}

export const relations: GraphRelation[] = [
  {
    id: 'sun-protection-is-used-for-sportswear',
    source: 'sun-protection-fabric',
    target: 'sportswear-athletic',
    type: 'is-used-for',
    label: { en: 'UPF 50+ sun protection fabrics are widely used in sportswear and athletic apparel', ko: '', ja: '', zh: '' },
  },
  {
    id: 'sun-protection-is-used-for-outdoor',
    source: 'sun-protection-fabric',
    target: 'outdoor-adventure',
    type: 'is-used-for',
    label: { en: 'Sun protection fabrics are essential for outdoor and adventure apparel', ko: '', ja: '', zh: '' },
  },
  {
    id: 'waterproof-is-used-for-outdoor',
    source: 'waterproof-fabric',
    target: 'outdoor-adventure',
    type: 'is-used-for',
    label: { en: 'Waterproof fabrics are essential for outdoor and adventure gear', ko: '', ja: '', zh: '' },
  },
  {
    id: 'waterproof-is-used-for-tactical',
    source: 'waterproof-fabric',
    target: 'tactical-workwear',
    type: 'is-used-for',
    label: { en: 'Waterproof fabrics are used in tactical and workwear applications', ko: '', ja: '', zh: '' },
  },
  {
    id: 'quick-dry-is-used-for-sportswear',
    source: 'quick-dry-fabric',
    target: 'sportswear-athletic',
    type: 'is-used-for',
    label: { en: 'Quick-dry moisture wicking fabrics are essential for sportswear and training apparel', ko: '', ja: '', zh: '' },
  },
  {
    id: 'quick-dry-is-used-for-fashion',
    source: 'quick-dry-fabric',
    target: 'fashion-casual',
    type: 'is-used-for',
    label: { en: 'Quick-dry fabrics are ideal for travel and casual summer wear', ko: '', ja: '', zh: '' },
  },
  {
    id: 'antibacterial-is-used-for-sportswear',
    source: 'antibacterial-fabric',
    target: 'sportswear-athletic',
    type: 'is-used-for',
    label: { en: 'Antibacterial fabrics are essential for sportswear odor control', ko: '', ja: '', zh: '' },
  },
  {
    id: 'antibacterial-is-used-for-medical',
    source: 'antibacterial-fabric',
    target: 'medical-protective',
    type: 'is-used-for',
    label: { en: 'Antibacterial fabrics are critical for medical and protective textiles', ko: '', ja: '', zh: '' },
  },
  {
    id: 'antibacterial-is-used-for-tactical',
    source: 'antibacterial-fabric',
    target: 'tactical-workwear',
    type: 'is-used-for',
    label: { en: 'Antibacterial treatment provides odor control for tactical and workwear uniforms', ko: '', ja: '', zh: '' },
  },
  {
    id: 'stretch-is-used-for-sportswear',
    source: 'stretch-fabric',
    target: 'sportswear-athletic',
    type: 'is-used-for',
    label: { en: '4-way stretch fabrics provide freedom of movement for athletic and yoga wear', ko: '', ja: '', zh: '' },
  },
  {
    id: 'stretch-is-used-for-tactical',
    source: 'stretch-fabric',
    target: 'tactical-workwear',
    type: 'is-used-for',
    label: { en: 'Mechanical stretch fabrics provide mobility for tactical and workwear pants', ko: '', ja: '', zh: '' },
  },
  {
    id: 'eco-friendly-is-used-for-fashion',
    source: 'eco-friendly-fabric',
    target: 'fashion-casual',
    type: 'is-used-for',
    label: { en: 'Eco-friendly recycled fabrics are increasingly used in sustainable fashion', ko: '', ja: '', zh: '' },
  },
  {
    id: 'eco-friendly-is-used-for-sportswear',
    source: 'eco-friendly-fabric',
    target: 'sportswear-athletic',
    type: 'is-used-for',
    label: { en: 'Recycled polyester is widely adopted in sustainable sportswear collections', ko: '', ja: '', zh: '' },
  },
  {
    id: 'breathable-is-used-for-sportswear',
    source: 'breathable-fabric',
    target: 'sportswear-athletic',
    type: 'is-used-for',
    label: { en: 'Breathable fabrics are essential for athletic comfort during high-intensity activity', ko: '', ja: '', zh: '' },
  },
  {
    id: 'breathable-is-used-for-fashion',
    source: 'breathable-fabric',
    target: 'fashion-casual',
    type: 'is-used-for',
    label: { en: 'Breathable fabrics provide comfort for summer fashion and casual wear', ko: '', ja: '', zh: '' },
  },
  {
    id: 'upf-uv-compatible-sun-protection',
    source: 'upf-uv-protection',
    target: 'sun-protection-fabric',
    type: 'is-compatible-with',
    label: { en: 'UPF/UV protection technology is the foundation of sun-protective fabrics', ko: '', ja: '', zh: '' },
  },
  {
    id: 'moisture-wicking-compatible-quick-dry',
    source: 'moisture-wicking-technology',
    target: 'quick-dry-fabric',
    type: 'is-compatible-with',
    label: { en: 'Moisture wicking technology is the core of quick-dry fabric performance', ko: '', ja: '', zh: '' },
  },
  {
    id: 'antibacterial-treatment-compatible-antibacterial',
    source: 'antibacterial-treatment-technology',
    target: 'antibacterial-fabric',
    type: 'is-compatible-with',
    label: { en: 'Silver ion antibacterial treatment provides the antimicrobial properties in our antibacterial fabrics', ko: '', ja: '', zh: '' },
  },
  {
    id: 'mechanical-stretch-compatible-stretch',
    source: 'mechanical-stretch-technology',
    target: 'stretch-fabric',
    type: 'is-compatible-with',
    label: { en: 'Mechanical stretch technology enables 4-way stretch without elastane', ko: '', ja: '', zh: '' },
  },
  {
    id: 'dwr-compatible-waterproof',
    source: 'dwr-finish',
    target: 'waterproof-fabric',
    type: 'is-compatible-with',
    label: { en: 'DWR finish provides water beading and complements waterproof coating technology', ko: '', ja: '', zh: '' },
  },
  {
    id: 'recycled-compatible-eco-friendly',
    source: 'recycled-polyester-technology',
    target: 'eco-friendly-fabric',
    type: 'is-compatible-with',
    label: { en: 'Recycled polyester technology enables GRS-certified eco-friendly fabric production', ko: '', ja: '', zh: '' },
  },
  {
    id: 'waterproof-coating-compatible-waterproof',
    source: 'waterproof-coating-technology',
    target: 'waterproof-fabric',
    type: 'is-compatible-with',
    label: { en: 'PU, TPU, and PVC coating technologies are the foundation of waterproof fabrics', ko: '', ja: '', zh: '' },
  },
  {
    id: 'mechanical-stretch-improves-comfort',
    source: 'mechanical-stretch-technology',
    target: 'moisture-wicking-technology',
    type: 'improves-on',
    label: {
      en: 'Mechanical stretch technology improves comfort and mobility in moisture-wicking performance fabrics',
      ko: '',
      ja: '',
      zh: '',
    },
  },
  {
    id: 'waterproof-coating-improves-weather',
    source: 'waterproof-coating-technology',
    target: 'dwr-finish',
    type: 'improves-on',
    label: {
      en: 'Waterproof coating provides a superior barrier compared to DWR finish alone for extreme weather conditions',
      ko: '',
      ja: '',
      zh: '',
    },
  },
  {
    id: 'recycled-polyester-enhances-eco',
    source: 'recycled-polyester-technology',
    target: 'eco-friendly-fabric',
    type: 'enhances',
    label: {
      en: 'Recycled polyester enhances the sustainability profile of eco-friendly fabric lines',
      ko: '',
      ja: '',
      zh: '',
    },
  },
  {
    id: 'upf-uv-enhances-sun-protection',
    source: 'upf-uv-protection',
    target: 'sun-protection-fabric',
    type: 'enhances',
    label: {
      en: 'UPF/UV fiber-level protection enhances the sun-blocking capability of our performance fabrics',
      ko: '',
      ja: '',
      zh: '',
    },
  },
];
